### ISSUE TITLE
Incorrect map behavior with Namespace

### ISSUE THREAD

**Issue by wavebeem** [minamorl/trishula#13]
It seems like `>=` is succeeding when it shouldn't. I don't have time to look more right now.

Output:

```
{'int': '47'}
{'status': <Status.SUCCEED: 1>, 'index': 2, 'value': 47, 'namespace': {}}
{'int': None}
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/brian/w/misc/pytesty/app/__main__.py", line 3, in <module>
    from . import simple_example
  File "/Users/brian/w/misc/pytesty/app/simple_example.py", line 18, in <module>
    main()
  File "/Users/brian/w/misc/pytesty/app/simple_example.py", line 14, in main
    result = T.Parser().parse(grammar, example)
  File "/Users/brian/.local/share/virtualenvs/pytesty-ptOPhfWe/lib/python3.7/site-packages/trishula/grammar.py", line 226, in parse
    result = grammar.parse(string, 0)
  File "/Users/brian/.local/share/virtualenvs/pytesty-ptOPhfWe/lib/python3.7/site-packages/trishula/grammar.py", line 192, in parse
    result.value = self.b(result.namespace)
  File "/Users/brian/w/misc/pytesty/app/simple_example.py", line 6, in handle
    return int(d["int"])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
The terminal process terminated with exit code: 1
```

```py
import trishula as T


def handle(d):
    print(d)
    return int(d["int"])


grammar = T.Namespace(T.Value("47") @ "int") >= handle


def main():
    for example in ('47', '"hi"'):
        result = T.Parser().parse(grammar, example)
        print(vars(result))


main()
```

**Comment by minamorl** [comment]
I cannot reproduce that.

**Comment by minamorl** [comment]
I've got:
```
{'int': '47'}
{'status': <Status.SUCCEED: 1>, 'index': 2, 'value': 47, 'namespace': {}}
{'status': <Status.FAILED: 2>, 'index': 0, 'value': None, 'namespace': {}}
```

**Comment by minamorl** [comment]
Please retry this with trishula 0.0.6. It will fix the problem.

**Comment by wavebeem** [comment]
ok, I will try tomorrow! 😃

**Comment by wavebeem** [comment]
0.0.6 fixes it, thanks!
