### ISSUE TITLE
Unexpected "None" value from Regexp parser

### ISSUE THREAD

**Issue by wavebeem** [minamorl/trishula#9]
```py
import trishula as T


# TODO: Escape characters
def json_string():
    return T.Namespace(
        T.Value("\"") >>
        (T.Regexp(r"[^\"]+") @ "value") >>
        T.Value("\"")
    ) >= (lambda d: d["value"])


# TODO: Scientific notation and other oddities
def json_number():
    return T.Regexp(r"[0-9]+") >= float


def json_value():
    return (
        (T.Value("true") >= (lambda _: True)) |
        (T.Value("false") >= (lambda _: False)) |
        (T.Value("null") >= (lambda _: None)) |
        json_number() |
        json_string()
    )


def grammar():
    return json_value()


def main():
    print(dir(T))
    print()
    examples = (
        '"hi"',
        "true",
        "false",
        "null",
        "2",
        # "3.14",
    )
    for ex in examples:
        result = T.Parser().parse(grammar(), ex)
        print(vars(result))


main()
```

OUTPUT:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/brian/w/pytesty/app/__main__.py", line 1, in <module>
    from . import json
  File "/Users/brian/w/pytesty/app/json.py", line 46, in <module>
    main()
  File "/Users/brian/w/pytesty/app/json.py", line 42, in main
    result = T.Parser().parse(grammar(), ex)
  File "/Users/brian/.local/share/virtualenvs/pytesty-LelHaWi2/lib/python3.7/site-packages/trishula/grammar.py", line 225, in parse
    result = grammar.parse(string, 0)
  File "/Users/brian/.local/share/virtualenvs/pytesty-LelHaWi2/lib/python3.7/site-packages/trishula/grammar.py", line 102, in parse
    resultA = self.a.parse(target, i)
  File "/Users/brian/.local/share/virtualenvs/pytesty-LelHaWi2/lib/python3.7/site-packages/trishula/grammar.py", line 105, in parse
    resultB = self.b.parse(target, resultA.index)
  File "/Users/brian/.local/share/virtualenvs/pytesty-LelHaWi2/lib/python3.7/site-packages/trishula/grammar.py", line 180, in parse
    result.value = self.b(result.value)
TypeError: float() argument must be a string or a number, not 'NoneType'
The terminal process terminated with exit code: 1
```

**Comment by minamorl** [comment]
Thanks for feedback. I will check it later.

**Comment by minamorl** [comment]
Hmm this is odd...

**Comment by minamorl** [comment]
Sorry for late. The problem is given string `"hi"` was passed to `float` unintentionally though parser was failed. It is a bug and now fixed.

**Comment by wavebeem** [comment]
Thank you for the fix! 🙇🏻‍♀️
